spring:
  datasource:
    url: jdbc:postgresql://db.fluxpognlnculkevzhko.supabase.co:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
  flyway:
    user: postgres
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        search:
          backend:
            lucene_version: 9.7.0
            directory.root: /data/search-index
