server:
  port: 8080
  address: 0.0.0.0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  main:
    web-application-type: servlet
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/placesandspaces-cbee6
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    validate-on-migrate: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

firebase:
  type: ${FIREBASE_ADMIN_SDK_TYPE}
  project_id: ${FIREBASE_ADMIN_SDK_PROJECT_ID}
  private_key_id: ${FIREBASE_ADMIN_SDK_PRIVATE_KEY_ID}
  private_key: ${FIREBASE_ADMIN_SDK_PRIVATE_KEY}
  client_email: ${FIREBASE_ADMIN_SDK_CLIENT_EMAIL}
  client_id: ${FIREBASE_ADMIN_SDK_CLIENT_ID}
  auth_uri: ${FIREBASE_ADMIN_SDK_AUTH_URI}
  token_uri: ${FIREBASE_ADMIN_SDK_TOKEN_URI}
  token_auth_provider_cert: ${FIREBASE_ADMIN_SDK_TOKEN_AUTH_PROVIDER_CERT}
  token_client_cert: ${FIREBASE_ADMIN_SDK_TOKEN_CLIENT_CERT}
  universe_domain: ${FIREBASE_ADMIN_SDK_UNIVERSE_DOMAIN}