spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
  flyway:
    user: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            lucene_version: 9.7.0
            directory.root: ./search-index

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE