spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
  flyway:
    user: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        search:
          backend:
            lucene_version: 9.7.0
            directory.root: ./search-index
