INSERT INTO business VALUES (1, 'hlrNMzmkYchokxFlLgwJrBqPVt92', 'BAR RASCAL',               null, 'rascal@rascal.com',             '767384943', 'Moliera 6',            'We are a winery that serves natural wine and seasonal food.', 'Wine Bar',     'MODERATE',    null, 52.2442, 21.0117, '2023-09-18');
INSERT INTO business VALUES (2, 'z82ya85oYeTH2RF42b2xvGWTMm33', 'Pizzaiolo',                null, 'pizzaiolo@pizzaiolo.com',       '867384943', 'Krucza 16/22',         'Neapolitan style pizza, drinks and vibes.',                   'Pizza',        'MODERATE',    null, 52.2258, 21.0192, '2023-09-18');
INSERT INTO business VALUES (3, '3PWYIeqNmkeld0zqBdOLOt7Uqus1', 'Señor Lucas taquería',     null, 'senorlucas@senorlucas.com',     '888313543', 'Poznańska 26',         'Come try our burritos and tacos',                             'Mexican',      'MODERATE',    null, 52.2268, 21.0112, '2023-09-18');
INSERT INTO business VALUES (4, 'ZF0etDfSgoSSKO7ldRkla80UPMG2', 'MOD',                      null, 'mod@mod.com',                   '720384943', 'Oleandrów 8',          'Come for our ramen and donuts',                               'Restaurant',   'MODERATE',    null, 52.2167, 21.0179, '2023-09-18');
INSERT INTO business VALUES (5, 'bFGBxxOBQbW2k3pksjFaCpueq963', 'POLLYPIZZA NEAPOLITAN',    null, 'pollypizza@pollypizza.com',     '636384333', 'Puławska 24',          'Neapolitan style pizza',                                      'Pizza',        'MODERATE',    null, 52.2069, 21.0219, '2023-09-18');
INSERT INTO business VALUES (6, 'j7BcUvoe1bOfzsuCrjmOaoAYqVp1', 'Efes',                     null, 'efes@efes.com',                 '767384222', 'Niepodległości 80',    'Turkish kebab',                                               'Kebab',        'MODERATE',    null, 52.1963, 21.0140, '2023-09-18');
INSERT INTO business VALUES (7, 's69plW7XqiXzJKEjDZROIsQonyM2', 'Izumi Sushi Biały Kamień', null, 'izumisushi@izumisushi.com',     '767384555', 'Biały Kamień 4',       'Best of sushi',                                               'Sushi',        'EXPENSIVE',   null, 52.2057, 20.9973, '2023-09-18');
INSERT INTO business VALUES (8, 'x329m1TruxOgY7aoBzAdiwCVd4p1', 'doskoi',                   null, 'doskoi@doskoi.com',             '753384466', 'Karmelicka 54/2',      'Traditional japanese food',                                   'Japanese',     'INEXPENSIVE', null, 50.0677, 19.9279, '2023-09-18');
INSERT INTO business VALUES (9, 'Xr9tE7j42KW6Nb202sMie9WBnck1', 'Czarna Kaczka',            null, 'czarnakaczka@czarnakaczka.com', '762334243', 'Poselska 22',          'Traditional polish food',                                     'Polish',       'EXPENSIVE',   null, 50.0582, 19.9392, '2023-09-18');
INSERT INTO business VALUES (10, 'RLGrMxsWzJOU4tGb90CuozLZVOs2', 'happa to mame',           null, 'happa@happa.com',               '575482121', 'Hoża 43/49',           'Matcha drinks and japanese sweets',                           'Matcha bar',   'EXPENSIVE',   null, 52.2255, 21.0114, '2023-09-18');
SELECT setval('business_id_seq', (SELECT MAX(id) from "business"));

INSERT INTO category VALUES(1, 'pizza');
INSERT INTO category VALUES(2, 'wine');
INSERT INTO category VALUES(3, 'italian');
INSERT INTO category VALUES(4, 'matcha');
INSERT INTO category VALUES(5, 'japanese');
INSERT INTO category VALUES(6, 'polish');
INSERT INTO category VALUES(7, 'kebab');
INSERT INTO category VALUES(8, 'ramen');
INSERT INTO category VALUES(9, 'mexican');
INSERT INTO category VALUES(10, 'sushi');
INSERT INTO category VALUES (11, 'fast food');
INSERT INTO category VALUES (12, 'fine dining');
INSERT INTO category VALUES (13, 'casual dining');
INSERT INTO category VALUES (14, 'ethnic cuisine');
INSERT INTO category VALUES (15, 'cafe');
INSERT INTO category VALUES (17, 'tea shop');
INSERT INTO category VALUES (18, 'food truck');
INSERT INTO category VALUES (19, 'street food');
INSERT INTO category VALUES (20, 'food cart');
INSERT INTO category VALUES (21, 'bakery');
INSERT INTO category VALUES (22, 'cake shop');
INSERT INTO category VALUES (23, 'donut');
INSERT INTO category VALUES (26, 'sports bar');
INSERT INTO category VALUES (27, 'brewpub');
INSERT INTO category VALUES (28, 'cocktail bar');
INSERT INTO category VALUES (29, 'ice cream');
INSERT INTO category VALUES (30, 'frozen yogurt');
INSERT INTO category VALUES (31, 'dessert');
INSERT INTO category VALUES (33, 'meal kit');
INSERT INTO category VALUES (34, 'event catering');
INSERT INTO category VALUES (35, 'corporate catering');
INSERT INTO category VALUES (36, 'wedding catering');
INSERT INTO category VALUES (38, 'snack manufacturing');
INSERT INTO category VALUES (39, 'beverage production');
INSERT INTO category VALUES (40, 'organic');
INSERT INTO category VALUES (41, 'health shop');
INSERT INTO category VALUES (44, 'cheese shop');
INSERT INTO category VALUES (45, 'dairy');
INSERT INTO category VALUES (46, 'seafood');
INSERT INTO category VALUES (49, 'vegan');
INSERT INTO category VALUES (50, 'vegetarian');
SELECT setval('business_id_seq', (SELECT MAX(id) from "business"));

INSERT INTO attribute VALUES (1, 'Bike parking');
INSERT INTO attribute VALUES (2, 'Accepts card');
INSERT INTO attribute VALUES (3, 'Dogs allowed');
INSERT INTO attribute VALUES (4, 'Outdoor seating');
INSERT INTO attribute VALUES (5, 'WiFi availability');
INSERT INTO attribute VALUES (6, 'Delivery');
INSERT INTO attribute VALUES (7, 'Takeout');
SELECT setval('attribute_id_seq', (SELECT MAX(id) from "attribute"));

INSERT INTO business_category VALUES (1, 1, 2);
INSERT INTO business_category VALUES (2, 2, 1);
INSERT INTO business_category VALUES (3, 3, 9);
INSERT INTO business_category VALUES (4, 4, 8);
INSERT INTO business_category VALUES (5, 5, 1);
INSERT INTO business_category VALUES (6, 6, 7);
INSERT INTO business_category VALUES (7, 7, 10);
INSERT INTO business_category VALUES (8, 8, 5);
INSERT INTO business_category VALUES (9, 9, 6);
INSERT INTO business_category VALUES (10, 10, 4);
SELECT setval('business_category_id_seq', (SELECT MAX(id) from "business_category"));

INSERT INTO business_attribute VALUES (1, 1, 2);
INSERT INTO business_attribute VALUES (2, 2, 1);
INSERT INTO business_attribute VALUES (3, 3, 3);
SELECT setval('business_attribute_id_seq', (SELECT MAX(id) from "business_attribute"));

INSERT INTO "user" VALUES (1, 'kMw6T9Dy6oZHAi4OvCWDnkUyVec2', 'test@gmail.com', 'test', 'test', null, '2023-11-10');
SELECT setval('user_id_seq', (SELECT MAX(id) from "user"));
